const ROLES = { LANDLORD: 'LANDLORD', TENANT: 'TENANT' };

const PROPERTY_TYPE = {
  APARTMENT: 'APARTMENT',
  HOUSE: 'HOUSE',
  ROOM: 'ROOM',
  COMMERCIAL: 'COMMERCIAL',
};

const PROPERTY_STATUS = {
  AVAILABLE: 'AVAILABLE',
  OCCUPIED: 'OCCUPIED',
  MAINTENANCE: 'MAINTENANCE',
};

const CONTRACT_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED',
  RENEWED: 'RENEWED',
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  UNDER_REVIEW: 'UNDER_REVIEW',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  REJECTED: 'REJECTED',
};

const PAYMENT_METHOD = {
  BANK_TRANSFER: 'BANK_TRANSFER',
  YAPE: 'YAPE',
  PLIN: 'PLIN',
  DEPOSIT: 'DEPOSIT',
  CASH: 'CASH',
};

const DOCUMENT_TYPE = {
  CONTRACT: 'CONTRACT',
  INVOICE: 'INVOICE',
  PAYMENT_RECEIPT: 'PAYMENT_RECEIPT',
  OTHER: 'OTHER',
};

const INCIDENT_TYPE = {
  COMPLAINT: 'COMPLAINT',
  CLAIM: 'CLAIM',
  MAINTENANCE_REQUEST: 'MAINTENANCE_REQUEST',
};

const INCIDENT_PRIORITY = { HIGH: 'HIGH', MEDIUM: 'MEDIUM', LOW: 'LOW' };

const INCIDENT_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
};

const SERVICE_TYPE = {
  WATER: 'WATER',
  ELECTRICITY: 'ELECTRICITY',
  INTERNET: 'INTERNET',
};

const NOTIFICATION_TYPE = {
  PAYMENT_DUE_SOON: 'PAYMENT_DUE_SOON',
  RECEIPT_UPLOADED: 'RECEIPT_UPLOADED',
  RECEIPT_APPROVED: 'RECEIPT_APPROVED',
  RECEIPT_REJECTED: 'RECEIPT_REJECTED',
  NEW_INCIDENT: 'NEW_INCIDENT',
  INCIDENT_RESPONSE: 'INCIDENT_RESPONSE',
  NEW_DOCUMENT: 'NEW_DOCUMENT',
  CONTRACT_EXPIRING: 'CONTRACT_EXPIRING',
};

module.exports = {
  ROLES,
  PROPERTY_TYPE,
  PROPERTY_STATUS,
  CONTRACT_STATUS,
  PAYMENT_STATUS,
  PAYMENT_METHOD,
  DOCUMENT_TYPE,
  INCIDENT_TYPE,
  INCIDENT_PRIORITY,
  INCIDENT_STATUS,
  SERVICE_TYPE,
  NOTIFICATION_TYPE,
};
